# ## FOR WINDOWS
# name: Auto-Deploy

# on:
#   push:
#     branches: [ "main" ]
#   repository_dispatch:
#     types: [ model_status_change ]

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Bypass PowerShell Execution Policy
#         shell: powershell
#         run: |
#           Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

#       - name: Kill Existing Uvicorn Server
#         shell: cmd
#         continue-on-error: true  # prevents pipeline failure if not running
#         run: |
#           taskkill /IM uvicorn.exe /F

#       - name: Activate Conda Environment and Install Dependencies
#         shell: cmd
#         run: |
#           call C:\Mudassir_LambdaTheta\MLOps\actions\Scripts\activate
#           pip install -r requirements.txt

#       - name: Start Uvicorn Server (Elevated)
#         shell: powershell
#         run: |
#           Start-Process `
#             -FilePath powershell `
#             -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File 'C:\Mudassir_LambdaTheta\MLOps\test_gitActions\start_server.bat'" `
#             -WindowStyle Normal `
#             -Verb RunAs
    
# # Following version is for cmd

name: Auto-Deploy
on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [ model_status_change ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Bypass PowerShell Execution Policy
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      
      - name: Stop FastAPI service
        shell: powershell
        run: |
          & 'C:\Users\LTPC\Downloads\nssm-2.24\nssm-2.24\win64\nssm.exe' stop MyFastAPI2
      
      - name: Update code in service folder
        shell: powershell
        run: |
          cd 'C:\Mudassir_LambdaTheta\MLOps\test_gitActions'
          git pull origin main
      
      - name: Activate Conda Environment and Install Dependencies
        shell: cmd
        run: |
          call C:\Mudassir_LambdaTheta\MLOps\actions\Scripts\activate
          pip install -r requirements.txt

      - name: Start FastAPI service
        shell: powershell
        run: |
          & 'C:\Users\LTPC\Downloads\nssm-2.24\nssm-2.24\win64\nssm.exe' start MyFastAPI2
        
