name: Auto-Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Bypass PowerShell Execution Policy just in case
      - name: Bypass PowerShell Execution Policy
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

      # ✅ Optional: Kill Existing Uvicorn Process (if needed)
      - name: Kill Existing Uvicorn Server
        shell: cmd
        # continue-on-error: true  # prevents pipeline failure if not running
        run: |
          taskkill /IM uvicorn.exe /F

      # ✅ Activate Conda Env & Install Requirements
      - name: Activate Conda Environment and Install Dependencies
        shell: cmd
        run: |
          call C:\Mudassir_LambdaTheta\MLOps\actions\Scripts\activate
          pip install -r requirements.txt

      # ✅ Start Uvicorn Server (⚠️ don't use `start ""` here)
      - name: Start Uvicorn Server
        shell: cmd
        run: |
          call C:\Mudassir_LambdaTheta\MLOps\actions\Scripts\activate
          start /B uvicorn main:app --host 0.0.0.0 --port 8000

